
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: secret
  pool: 5

development:
  <<: *default
  database: devise_jwt_development


# test:
#   <<: *default
#   database: myapp_test

# production:
#   <<: *default
#   database: myapp_production